#!/bin/sh
#
# (c) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT license
#

# Run /init time

export bbx=/bin/busybox bttm=$($bbx date +%s%N)

# busybox install

export TERM=xterm PATH=/bin:/sbin:/usr/bin:/usr/sbin ENV=/etc/profile

$bbx mount -o remount,rw /
$bbx mkdir -p /dev /proc /sys /tmp /etc/init.d /var/log /root /home
$bbx --install -s
touch /etc/inittab
touch /etc/fstab
sync

# system uprising

mount -t sysfs sysfs /sys
echo Y > /sys/module/printk/parameters/time
test -r  /lib/modules/uchaos_dev.ko &&
  insmod /lib/modules/uchaos_dev.ko badb_init=1

mount -t proc procfs /proc
grep -q uchaos_dev /proc/modules &&
  while usleep 9999; do dmesg | grep -q "uchaos: kmod loop=" && break; done
echo 3 >/proc/sys/kernel/printk

mount -o size=16k,nosuid -t devtmpfs tmpfs /dev
mkdir -p /dev/pts && mount -t devpts devpts /dev/pts

# 2nd stage init

touch /etc/init.d/rcS
chmod +x /etc/init.d/rcS
exec /linuxrc
stty -echoctl
printf "\e[?7hRun /init exec /linuxrc\n"
echo
echo "Emergency shell respowning because /linuxrc failed"
echo
while true; do /bin/sh; sleep 1; done
