#
# (c) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT license
#     Copyright notice and related license applies to the changes, original
#     Makefile remains under the terms and authorship as previously it was.
#

TOPDIR ?= $(shell realpath ../../..)
OUTPUT := $(TOPDIR)/output

BINUTILS_SRCDIR = BINUTILS_SRCDIR_not_set
GCC_SRCDIR = GCC_SRCDIR_not_set
MUSL_SRCDIR = MUSL_SRCDIR_not_set

GCC_CONFIG_FOR_TARGET =
COMMON_CONFIG =
GCC_CONFIG =
TOOLCHAIN_CONFIG =

XGCC_DIR = ../obj_gcc/gcc
XGCC = $(XGCC_DIR)/xgcc -B $(XGCC_DIR)

-include config.mak

ifneq ($(findstring fdpic,$(TARGET)),)
GCC_CONFIG_FOR_TARGET += --enable-fdpic
endif

ifneq ($(filter x86_64%x32,$(TARGET)),)
GCC_CONFIG_FOR_TARGET += --with-abi=x32
endif

ifneq ($(findstring powerpc64,$(TARGET)),)
GCC_CONFIG_FOR_TARGET += --with-abi=elfv2
endif

ifneq ($(findstring mips64,$(TARGET))$(findstring mipsisa64,$(TARGET)),)
ifneq ($(findstring n32,$(TARGET)),)
GCC_CONFIG_FOR_TARGET += --with-abi=n32
else
GCC_CONFIG_FOR_TARGET += --with-abi=64
endif
endif

ifneq ($(findstring s390x,$(TARGET)),)
GCC_CONFIG_FOR_TARGET += --with-long-double-128
endif

ifneq ($(filter %sf,$(TARGET)),)
GCC_CONFIG_FOR_TARGET += --with-float=soft
endif

ifneq ($(filter %hf,$(TARGET)),)
GCC_CONFIG_FOR_TARGET += --with-float=hard
endif

ifneq ($(LIBTOOL),)
LIBTOOL_ARG = LIBTOOL=$(LIBTOOL)
endif

GCC_CONFIG_FOR_TARGET += HAVE_DECL_BASENAME=1
LIBTOOL_ARG += HAVE_DECL_BASENAME=1

MAKE += HAVE_DECL_BASENAME=1
MAKE += MULTILIB_OSDIRNAMES=
MAKE += INFO_DEPS= infodir=
MAKE += ac_cv_prog_lex_root=lex.yy
MAKE += gcc_cv_have_decl_basename=yes
MAKE +=  ac_cv_have_decl_basename=yes
MAKE +=  ac_cv_func_basename=yes
MAKE += MAKEINFO=false

FULL_BINUTILS_CONFIG = \
	--disable-separate-code \
	$(COMMON_CONFIG) $(BINUTILS_CONFIG) $(TOOLCHAIN_CONFIG) \
	--disable-werror \
	--target=$(TARGET) --prefix= \
	--libdir=/lib --disable-multilib --disable-shared \
	--with-sysroot=$(SYSROOT) \
	--enable-deterministic-archives

FULL_GCC_CONFIG = --enable-languages=c,c++ \
	$(GCC_CONFIG_FOR_TARGET) \
	$(COMMON_CONFIG) $(GCC_CONFIG) $(TOOLCHAIN_CONFIG) \
	--disable-bootstrap \
	--disable-assembly \
	--disable-werror \
	--target=$(TARGET) --prefix= \
	--libdir=/lib --disable-multilib --disable-shared \
	--with-sysroot=$(SYSROOT) \
	--enable-tls \
	--disable-libmudflap --disable-libsanitizer \
	--disable-gnu-indirect-function \
	--disable-libmpx \
	--enable-initfini-array \
	--enable-libstdcxx-time=rt

FULL_MUSL_CONFIG = $(MUSL_CONFIG) \
	--prefix= --host=$(HOST)

FULL_ZLIB_CONFIG = --static --disable-crcvx \
	--prefix= --host=$(HOST)

FULL_PCRE2_CONFIG = --disable-shared \
	--prefix= --host=$(HOST)

NINJA  := ninja
MESON  := $(TOPDIR)/output/bin/meson.pyz
PKGCFG := $(TOPDIR)/output/usr/bin/pkg-config

FULL_GLIB_CONFIG = -Dtests=false --prefix=/ \
  --buildtype=release --default-library=static \
  --strip --optimization 1 --wrap-mode=forcefallback \
  -Dman-pages=disabled -Ddocumentation=false -Dintrospection=disabled \
  -Dselinux=disabled -Dxattr=false

##  --wrap-mode=nodownload -Dzlib=enabled -Dpcre2=enabled -Dlibffi=enabled
#
#  -DHAVE_DECL_BASENAME=1
#--buildtype release --prefer-static --strip --optimization 1 \
#	  --includedir $(OUTPUT)/include/ --cross-file cross.ini obj_glib src_glib \
#	    --wrap-mode=forcefallback --prefix=/ -Dtests=false -Ddefault_library=static

ifneq ($(NATIVE),)
HOST:=$(TARGET)
endif

ifeq ($(BUILD),)
GUESS = $(shell cd $(GCC_SRCDIR) && ./config.guess)
TARGET_CANON = $(shell cd $(GCC_SRCDIR) && ./config.sub $(TARGET))
BUILD = $(GUESS)$(if $(subst $(TARGET_CANON),,$(GUESS)),,xx)
endif

ifeq ($(HOST),)
SYSROOT =  # /$(TARGET)
FULL_BINUTILS_CONFIG += --build=$(BUILD) --host=$(BUILD)
FULL_GCC_CONFIG += --with-build-sysroot=$(CURDIR)/obj_sysroot \
	AR_FOR_TARGET=$(PWD)/obj_binutils/binutils/ar \
	AS_FOR_TARGET=$(PWD)/obj_binutils/gas/as-new \
	LD_FOR_TARGET=$(PWD)/obj_binutils/ld/ld-new \
	NM_FOR_TARGET=$(PWD)/obj_binutils/binutils/nm-new \
	OBJCOPY_FOR_TARGET=$(PWD)/obj_binutils/binutils/objcopy \
	OBJDUMP_FOR_TARGET=$(PWD)/obj_binutils/binutils/objdump \
	RANLIB_FOR_TARGET=$(PWD)/obj_binutils/binutils/ranlib \
	READELF_FOR_TARGET=$(PWD)/obj_binutils/binutils/readelf \
	STRIP_FOR_TARGET=$(PWD)/obj_binutils/binutils/strip-new \
	--build=$(BUILD) --host=$(BUILD) \
	# end
FULL_MUSL_CONFIG += CC="$(XGCC)" LIBCC="../obj_gcc/$(TARGET)/libgcc/libgcc.a"
MUSL_VARS = AR=../obj_binutils/binutils/ar RANLIB=../obj_binutils/binutils/ranlib
obj_musl/.lc_configured: | obj_gcc/gcc/.lc_built
obj_musl/.lc_built: | obj_gcc/$(TARGET)/libgcc/libgcc.a
obj_gcc/gcc/.lc_built: | obj_sysroot/usr obj_sysroot/lib32 obj_sysroot/lib64 obj_sysroot/include
obj_gcc/.lc_built: | obj_sysroot/.lc_libs obj_sysroot/.lc_headers
obj_gcc/.lc_configured: obj_binutils/.lc_built
else
SYSROOT = /
FULL_BINUTILS_CONFIG += --build=$(BUILD) --host=$(HOST)
FULL_GCC_CONFIG += --build=$(BUILD) --host=$(HOST)
MUSL_VARS =
endif

# Activate colors
CFLAGS += -fdiagnostics-color=always
CXXFLAGS += -fdiagnostics-color=always

ifeq ($(TARGET),)

all:
	@echo TARGET must be set.
	@exit 1

install: all

else

all: musl toolchain
# extra-libs

install: install-musl install-toolchain
# install-libs

musl: obj_musl/.lc_built

toolchain: gcc binutils

extra-libs: zlib pcre2

install-toolchain: install-gcc install-binutils install-meson

install-libs: install-pcre2 install-zlib

binutils: obj_binutils/.lc_built

gcc: obj_gcc/.lc_built

zlib: obj_zlib/.lc_built

pcre2: obj_pcre2/.lc_built

src_meson/meson.pyz: src_meson
	cd src_meson && python3 packaging/create_zipapp.py \
	  --outfile meson.pyz --interpreter '/usr/bin/env python3' .

install-meson: src_meson/meson.pyz
	mkdir -p $(dir $(MESON))
	cp -aflL $(MESON_SRCDIR)/meson.pyz $(MESON)

glib: install-glib

.PHONY: all musl toolchain extra-libs glib install-glib clean
.PHONY: install-musl install-toolchain install-meson install-libs

src_binutils: | $(BINUTILS_SRCDIR)
	ln -sf $(BINUTILS_SRCDIR) $@

src_gcc_base: | $(GCC_SRCDIR)
	ln -sf $(GCC_SRCDIR) $@

src_musl: | $(MUSL_SRCDIR)
	ln -sf $(MUSL_SRCDIR) $@

ifneq ($(PCRE2_SRCDIR),)
src_pcre2: | $(PCRE2_SRCDIR)
	ln -sf $(PCRE2_SRCDIR) $@
endif

ifneq ($(MESON_SRCDIR),)
src_meson: | $(MESON_SRCDIR)
	ln -sf $(MESON_SRCDIR) $@
endif

ifneq ($(ZLIB_SRCDIR),)
src_zlib: | $(ZLIB_SRCDIR)
	ln -sf $(ZLIB_SRCDIR) $@
endif

ifneq ($(GLIB_SRCDIR),)
src_glib: | $(GLIB_SRCDIR)
	ln -sf $(GLIB_SRCDIR) $@
	rm -rf $@/.git*
endif

ifneq ($(GMP_SRCDIR),)
src_gcc: src_gmp
src_gmp: | $(GMP_SRCDIR)
	ln -sf "$(GMP_SRCDIR)" $@
endif

ifneq ($(MPC_SRCDIR),)
src_gcc: src_mpc
src_mpc: | $(MPC_SRCDIR)
	ln -sf "$(MPC_SRCDIR)" $@
endif

ifneq ($(MPFR_SRCDIR),)
src_gcc: src_mpfr
src_mpfr: | $(MPFR_SRCDIR)
	ln -sf "$(MPFR_SRCDIR)" $@
endif

ifneq ($(ISL_SRCDIR),)
src_gcc: src_isl
src_isl: | $(ISL_SRCDIR)
	ln -sf "$(ISL_SRCDIR)" $@
endif

src_gcc: src_gcc_base
	rm -rf $@ $@.tmp
	mkdir $@.tmp
	cd $@.tmp && ln -sf ../src_gcc_base/* .
	$(if $(GMP_SRCDIR),cd $@.tmp && ln -sf ../src_gmp gmp)
	$(if $(MPC_SRCDIR),cd $@.tmp && ln -sf ../src_mpc mpc)
	$(if $(MPFR_SRCDIR),cd $@.tmp && ln -sf ../src_mpfr mpfr)
	$(if $(ISL_SRCDIR),cd $@.tmp && ln -sf ../src_isl isl)
	mv $@.tmp $@

obj_%:
	mkdir -p $@

obj_sysroot/include:
	mkdir -p $@

obj_sysroot/usr:   | obj_sysroot
	ln -sf . $@

obj_sysroot/lib32: | obj_sysroot
	ln -sf lib $@

obj_sysroot/lib64: | obj_sysroot
	ln -sf lib $@

obj_binutils/.lc_configured: | obj_binutils src_binutils
	cd obj_binutils && ../src_binutils/configure $(FULL_BINUTILS_CONFIG)
	touch $@

obj_binutils/.lc_built: | obj_binutils/.lc_configured
	$(MAKE) MAKE="$(MAKE) $(LIBTOOL_ARG)" -C obj_binutils all
	touch $@

obj_gcc/.lc_configured: | obj_gcc src_gcc
	cd obj_gcc && ../src_gcc/configure $(FULL_GCC_CONFIG)
	touch $@

obj_gcc/gcc/.lc_built: | obj_gcc/.lc_configured
	$(MAKE) MAKE="$(MAKE) $(LIBTOOL_ARG)" -C obj_gcc all-gcc
	touch $@

obj_musl/.lc_configured: | obj_musl src_musl
	cd obj_musl && ../src_musl/configure $(FULL_MUSL_CONFIG)
	touch $@

obj_sysroot/.lc_headers: | obj_musl/.lc_configured obj_sysroot
	$(MAKE) DESTDIR=$(CURDIR)/obj_sysroot -C obj_musl install-headers
	touch $@

obj_gcc/$(TARGET)/libgcc/libgcc.a: | obj_sysroot/.lc_headers
	$(MAKE) MAKE="$(MAKE) enable_shared=no $(LIBTOOL_ARG)" -C obj_gcc all-target-libgcc

obj_musl/.lc_built: | obj_musl/.lc_configured
	$(MAKE) $(MUSL_VARS) -C obj_musl
	touch $@

obj_sysroot/.lc_libs: | obj_musl/.lc_built
	$(MAKE) $(MUSL_VARS) DESTDIR=$(CURDIR)/obj_sysroot -C obj_musl install
	touch $@

obj_zlib/.lc_configured: | obj_zlib src_zlib obj_sysroot/.lc_headers
	cd obj_zlib && ../src_zlib/configure $(FULL_ZLIB_CONFIG)
	touch $@

obj_zlib/.lc_built: | obj_zlib/.lc_configured
	$(MAKE) MAKE="$(MAKE)" -C obj_zlib # DESTDIR=$(CURDIR)/obj_sysroot install
	touch $@

obj_pcre2/.lc_configured: | obj_pcre2 src_pcre2 obj_sysroot/.lc_headers
	cd obj_pcre2 && ../src_pcre2/configure $(FULL_PCRE2_CONFIG)
	touch $@

obj_pcre2/.lc_built: | obj_pcre2/.lc_configured
	$(MAKE) MAKE="$(MAKE)" -C obj_pcre2 # DESTDIR=$(CURDIR)/obj_sysroot install
	touch $@

obj_glib/.lc_configured: | src_glib obj_sysroot/.lc_headers obj_glib
	sed -i '/add_test_setup(.thorough./,+5d' src_glib/meson.build
	MESON=$(MESON) PKGCFG="" PREFIX="" sh -x $(TOPDIR)/../cnfg/cross.sh cross.ini
	$(MESON) setup $(FULL_GLIB_CONFIG) --cross-file cross.ini obj_glib src_glib
	touch $@
# $(ARCH)-linux-musl- # $(PKGCFG)

obj_glib/.lc_built: obj_glib/.lc_configured
	$(NINJA) -C obj_glib
	touch $@

obj_gcc/.lc_built: | obj_gcc/.lc_configured obj_gcc/gcc/.lc_built
	$(MAKE) MAKE="$(MAKE) $(LIBTOOL_ARG)" -C obj_gcc
	touch $@

install-musl: | obj_musl/.lc_built
	$(MAKE) $(MUSL_VARS) DESTDIR=$(OUTPUT)$(SYSROOT) -C obj_musl install

install-binutils: | obj_binutils/.lc_built
	$(MAKE) MAKE="$(MAKE) $(LIBTOOL_ARG)" DESTDIR=$(OUTPUT) -C obj_binutils install

install-gcc: | obj_gcc/.lc_built
	$(MAKE) MAKE="$(MAKE) $(LIBTOOL_ARG)" DESTDIR=$(OUTPUT) -C obj_gcc install
	ln -sf $(TARGET)-gcc $(OUTPUT)/bin/$(TARGET)-cc

install-zlib: | obj_zlib/.lc_built
	$(MAKE) MAKE="$(MAKE)" DESTDIR=$(OUTPUT)$(SYSROOT) -C obj_zlib install

install-pcre2: | obj_pcre2/.lc_built
	$(MAKE) MAKE="$(MAKE)" DESTDIR=$(OUTPUT)$(SYSROOT) -C obj_pcre2 install

install-glib: | obj_glib/.lc_built
	DESTDIR=$(CURDIR) $(NINJA) -C obj_glib install

ifneq ($(LINUX_SRCDIR),)
TARGET_ARCH = $(firstword $(subst -, ,$(TARGET)))
TARGET_ARCH_MANGLED = $(patsubst or1k,openrisc,$(patsubst i%86,x86,$(patsubst aarch64%,arm64%,$(TARGET_ARCH))))
LINUX_ARCH_LIST = $(sort $(notdir $(wildcard $(LINUX_SRCDIR)/arch/*)))
LINUX_ARCH = $(lastword $(foreach a,$(LINUX_ARCH_LIST),$(if $(filter $(a)%,$(TARGET_ARCH_MANGLED)),$(a))))
ifneq ($(LINUX_ARCH),)
all: kernel-headers
install: install-kernel-headers
kernel-headers: | obj_kernel_headers/.lc_built
src_kernel_headers: | $(LINUX_SRCDIR)
	ln -sf "$(LINUX_SRCDIR)" $@
obj_kernel_headers/.lc_built: | src_kernel_headers
	mkdir -p $(CURDIR)/obj_kernel_headers/staged
	cd src_kernel_headers && $(MAKE) ARCH=$(LINUX_ARCH) O=$(CURDIR)/obj_kernel_headers INSTALL_HDR_PATH=$(CURDIR)/obj_kernel_headers/staged headers_install
	find obj_kernel_headers/staged/include '(' -name .install -o -name ..install.cmd ')' -exec rm {} +
	touch $@
install-kernel-headers: | obj_kernel_headers/.lc_built
	mkdir -p $(OUTPUT)$(SYSROOT)/include
	cp -R obj_kernel_headers/staged/include/* $(OUTPUT)$(SYSROOT)/include
endif
endif

endif

clean:
	rm -rf src_* obj_*

