#
# (c) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT license
#     Copyright notice and related license applies to the changes, original
#     Original remains under the terms and authorship as previously it was.
#

SOURCES = sources

CONFIG_SUB_REV = a2287c3041a3
BINUTILS_VER = 2.44
GCC_VER = 14.3.0
MUSL_VER = 1.2.5
GMP_VER = 6.3.0
MPC_VER = 1.3.1
MPFR_VER = 4.2.2
ISL_VER = 0.27
ZLIB_VER = 1.3.2
PCRE2_VER = 10.47
MESON_VER = 1.10.2
NINJIA_VER = 1.13.2
GLIB_VER = 2.88.0

# Target platform, kernel version and gcc/ld options are set by config.mak
# LINUX_VER = 5.15.202

USR_SITE = https://github.com/robang74
GNU_SITE = https://ftpmirror.gnu.org/gnu
# Skip url redirection and quey a specific server
# GNU_SITE = https://ftp.fau.de/gnu

BINUTILS_SITE = $(GNU_SITE)/binutils
GCC_SITE = $(GNU_SITE)/gcc
GMP_SITE = $(GNU_SITE)/gmp
MPC_SITE = $(GNU_SITE)/mpc
MPFR_SITE = $(GNU_SITE)/mpfr
# ISL_SITE = https://libisl.sourceforge.io
ISL_SITE = $(USR_SITE)/isl/archive/refs/tags
ZLIB_SITE = $(USR_SITE)/zlib/archive/refs/tags
PCRE2_SITE = $(USR_SITE)/pcre2/archive/refs/tags
MESON_SITE = $(USR_SITE)/meson/archive/refs/tags

MUSL_SITE = https://musl.libc.org/releases
MUSL_REPO = https://git.musl-libc.org/git/musl

LINUX_SITE = https://cdn.kernel.org/pub/linux/kernel
LINUX_HEADERS_SITE = https://ftp.barfooze.de/pub/sabotage/tarballs

GLIB_SITE = https://download.gnome.org/sources/glib/$(shell echo $(GLIB_VER) | cut -d. -f1,2)

DL_CMD = wget -c -O
SHA1_CMD = sha1sum -c

COWPATCH = $(CURDIR)/cowpatch.sh

HOST = $(if $(NATIVE),$(TARGET))
OUTPUT = $(CURDIR)/output$(if $(HOST),-$(HOST))
BUILD_DIR = build/$(if $(HOST),$(HOST),local)/$(TARGET)

REL_TOP = ../../..

-include config.mak

SRC_DIRS = gcc-$(GCC_VER) binutils-$(BINUTILS_VER) musl-$(MUSL_VER) \
	$(if $(GMP_VER),gmp-$(GMP_VER)) \
	$(if $(MPC_VER),mpc-$(MPC_VER)) \
	$(if $(MPFR_VER),mpfr-$(MPFR_VER)) \
	$(if $(ISL_VER),isl-$(ISL_VER)) \
	$(if $(ZLIB_VER),zlib-$(ZLIB_VER)) \
	$(if $(PCRE2_VER),pcre2-$(PCRE2_VER)) \
	$(if $(MESON_VER),meson-$(MESON_VER)) \
	$(if $(GLIB_VER),glib-$(GLIB_VER)) \
	$(if $(LINUX_VER),linux-$(LINUX_VER))

all:

clean:
	rm -rf build-* build/

veryclean: clean
	rm -rf gcc-* binutils-* musl-* isl-*
	rm -rf mpfr-* mpc-* pcre2-* linux-*
	rm -rf gmp-* zlib-* glib-* meson-*
	rm -rf $(OUTPUT)/

distclean: veryclean
	rm -rf $(SOURCES)/


# Rules for downloading and verifying sources. Treat an external SOURCES path as
# immutable and do not try to download anything into it.

ifeq ($(SOURCES),sources) ######################################################

$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/binutils*)): SITE = $(BINUTILS_SITE)
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/gcc*)): SITE = $(GCC_SITE)/$(basename $(basename $(notdir $@)))
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/gmp*)): SITE = $(GMP_SITE)
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/mpc*)): SITE = $(MPC_SITE)
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/mpfr*)): SITE = $(MPFR_SITE)
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/isl*)): SITE = $(ISL_SITE)
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/musl*)): SITE = $(MUSL_SITE)
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/zlib*)): SITE = $(ZLIB_SITE)
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/pcre2*)): SITE = $(PCRE2_SITE)
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/meson*)): SITE = $(MESON_SITE)
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/glib*)): SITE = $(GLIB_SITE)
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/linux-6*)): SITE = $(LINUX_SITE)/v6.x
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/linux-5*)): SITE = $(LINUX_SITE)/v5.x
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/linux-4*)): SITE = $(LINUX_SITE)/v4.x
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/linux-3*)): SITE = $(LINUX_SITE)/v3.x
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/linux-2.6*)): SITE = $(LINUX_SITE)/v2.6
$(patsubst hashes/%.sha1,$(SOURCES)/%,$(wildcard hashes/linux-headers-*)): SITE = $(LINUX_HEADERS_SITE)

$(SOURCES):
	mkdir -p $@

$(SOURCES)/config.sub: | $(SOURCES)
	echo "MUSL >>> $@: $^"
	mkdir -p $@.tmp
	cd $@.tmp && $(DL_CMD) $(notdir $@) "https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=$(CONFIG_SUB_REV)"
	cd $@.tmp && touch $(notdir $@)
	cd $@.tmp && $(SHA1_CMD) $(CURDIR)/hashes/$(notdir $@).$(CONFIG_SUB_REV).sha1
	mv $@.tmp/$(notdir $@) $@
	rm -rf $@.tmp

$(SOURCES)/%.ok: hashes/%.sha1 | $(SOURCES)
	echo "MUSL >>> $@: $^"
	mkdir -p $@.tmp
	cd $@.tmp && $(DL_CMD) $(notdir $@) $(SITE)/$(notdir $@)
	cd $@.tmp && touch $(notdir $@)
	cd $@.tmp && $(SHA1_CMD) $(CURDIR)/hashes/$(notdir $@).sha1
	mv $@.tmp/$(notdir $@) $@
	rm -rf $@.tmp
	touch $@.ok

$(SOURCES)/%: $(SOURCES)/%.ok

endif ##########################################################################


# Rules for extracting and patching sources, or checking them out from git.

define extract_tar
	case "$1" in */*) exit 1 ;; esac
	rm -rf $1.tmp ; mkdir $1.tmp
	tar -C $1.tmp --strip-components=1 -$2 $3
	rm -rf $1 ; mv $1.tmp/ $1 ; touch $1
endef

musl-git-%:
	echo "MUSL >>> $@: $^"
	rm -rf $@.tmp
	git clone -b $(patsubst musl-git-%,%,$@) $(MUSL_REPO) $@.tmp
	cd $@.tmp && git fsck
	mv $@.tmp $@ ; touch $@

%.orig: $(SOURCES)/%.tar.gz
	$(call extract_tar,$@,xzf,$<)

%.orig: $(SOURCES)/%.tar.bz2
	$(call extract_tar,$@,xjf,$<)

%.orig: $(SOURCES)/%.tar.xz
	$(call extract_tar,$@,xJf,$<)

%: %.orig
	echo "MUSL >>> $@: $^"
	case "$@" in */*) exit 1 ;; esac
	rm -rf $@.tmp ; mkdir $@.tmp; cd $@.tmp && $(COWPATCH) -I ../$<
	test ! -d patches/$@ || cat patches/$@/* | ( cd $@.tmp && $(COWPATCH) -p1 )
	rm -rf $@ ; mv $@.tmp $@ ; touch $@


# Add deps for all patched source dirs on their patchsets
$(foreach dir,$(notdir $(basename $(basename $(basename $(wildcard hashes/*))))),$(eval $(dir): $$(wildcard patches/$(dir) patches/$(dir)/*)))

extract_all: | $(SRC_DIRS)

# Rules for building.

ifeq ($(TARGET),)

all:
	@echo TARGET must be set via config.mak or command line.
	@exit 1

else

$(BUILD_DIR):
	echo "MUSL >>> $@: $^"
	mkdir -p $@

$(BUILD_DIR)/Makefile: | $(BUILD_DIR)
	echo "MUSL >>> $@: $^"
	ln -sf $(REL_TOP)/litecross/Makefile $@

$(BUILD_DIR)/config.mak: | $(BUILD_DIR)
	echo "MUSL >>> $@: $^"
	printf >$@ '%s\n' \
	"TARGET = $(TARGET)" \
	"HOST = $(HOST)" \
	"MUSL_SRCDIR = $(REL_TOP)/musl-$(MUSL_VER)" \
	"GCC_SRCDIR = $(REL_TOP)/gcc-$(GCC_VER)" \
	"BINUTILS_SRCDIR = $(REL_TOP)/binutils-$(BINUTILS_VER)" \
	$(if $(GMP_VER),"GMP_SRCDIR = $(REL_TOP)/gmp-$(GMP_VER)") \
	$(if $(MPC_VER),"MPC_SRCDIR = $(REL_TOP)/mpc-$(MPC_VER)") \
	$(if $(MPFR_VER),"MPFR_SRCDIR = $(REL_TOP)/mpfr-$(MPFR_VER)") \
	$(if $(ISL_VER),"ISL_SRCDIR = $(REL_TOP)/isl-$(ISL_VER)") \
	$(if $(ZLIB_VER),"ZLIB_SRCDIR = $(REL_TOP)/zlib-$(ZLIB_VER)") \
	$(if $(PCRE2_VER),"PCRE2_SRCDIR = $(REL_TOP)/pcre2-$(PCRE2_VER)") \
	$(if $(MESON_VER),"MESON_SRCDIR = $(REL_TOP)/meson-$(MESON_VER)") \
	$(if $(GLIB_VER),"GLIB_SRCDIR = $(REL_TOP)/glib-$(GLIB_VER)") \
	$(if $(LINUX_VER),"LINUX_SRCDIR = $(REL_TOP)/linux-$(LINUX_VER)") \
	"-include $(REL_TOP)/config.mak"

all: | $(SRC_DIRS) $(BUILD_DIR) $(BUILD_DIR)/Makefile $(BUILD_DIR)/config.mak
	cd $(BUILD_DIR) && $(MAKE) $@

glib:
	cd $(BUILD_DIR) && $(MAKE) $@

install: | $(SRC_DIRS) $(BUILD_DIR) $(BUILD_DIR)/Makefile $(BUILD_DIR)/config.mak
	cd $(BUILD_DIR) && $(MAKE) OUTPUT=$(OUTPUT) $@

endif

.SECONDARY:
