#!/bin/sh
#
# (c) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT license
#
################################################################################

--- a/hw/i386/acpi-build.c	2026-03-24 14:23:37.852944753 +0100
+++ b/hw/i386/acpi-build.c	2026-03-24 14:26:02.097386643 +0100
@@ -839,7 +839,9 @@ static void build_acpi0017(Aml *table)
     method = aml_method("_STA", 0, AML_NOTSERIALIZED);
     aml_append(method, aml_return(aml_int(0x0B)));
     aml_append(dev, method);
-    build_cxl_dsm_method(dev);
+ #ifndef _DISABLE_CXL //RAF: disable for a minimal build
+    build_cxl_dsm_method(dev);
+ #endif

     aml_append(scope, dev);
     aml_append(table, scope);
@@ -1014,7 +1015,9 @@ build_dsdt(GArray *table_data, BIOSLinke
                 aml_append(aml_pkg, aml_eisaid("PNP0A08"));
                 aml_append(aml_pkg, aml_eisaid("PNP0A03"));
                 aml_append(dev, aml_name_decl("_CID", aml_pkg));
-                build_cxl_osc_method(dev);
+ #ifndef _DISABLE_CXL //RAF: disable for a minimal build
+                build_cxl_osc_method(dev);
+ #endif
             } else if (pci_bus_is_express(bus)) {
                 aml_append(dev, aml_name_decl("_HID", aml_eisaid("PNP0A08")));
                 aml_append(dev, aml_name_decl("_CID", aml_eisaid("PNP0A03")));
@@ -2072,8 +2074,10 @@ void acpi_build(AcpiBuildTables *tables,
                           x86ms->oem_id, x86ms->oem_table_id);
     }
     if (pcms->cxl_devices_state.is_enabled) {
-        cxl_build_cedt(table_offsets, tables_blob, tables->linker,
-                       x86ms->oem_id, x86ms->oem_table_id, &pcms->cxl_devices_state);
+ #ifndef _DISABLE_CXL //RAF: disable for a minimal build
+        cxl_build_cedt(table_offsets, tables_blob, tables->linker,
+                       x86ms->oem_id, x86ms->oem_table_id, &pcms->cxl_devices_state);
+ #endif
     }

     acpi_add_table(table_offsets, tables_blob);
--- a/hw/pci-host/gpex-acpi.c	2026-03-24 14:57:57.740528905 +0100
+++ b/hw/pci-host/gpex-acpi.c	2026-03-24 14:58:50.833630475 +0100
@@ -149,7 +119,9 @@ void acpi_dsdt_add_gpex(Aml *scope, stru
             aml_append(dev, aml_name_decl("_CRS", crs));

             if (is_cxl) {
-                build_cxl_osc_method(dev);
+ #ifndef _DISABLE_CXL //RAF: disable for a minimal build
+                build_cxl_osc_method(dev);
+ #endif
             } else {
                 /* pxb bridges do not have ACPI PCI Hot-plug enabled */
                 acpi_dsdt_add_host_bridge_methods(dev, true);
--- a/hw/i386/pc_q35.c	2026-03-31 19:10:11.650911367 +0200
+++ b/hw/i386/pc_q35.c	2026-03-31 19:11:06.445131700 +0200
@@ -79,7 +79,7 @@ struct ehci_companions {
     int func;
     int port;
 };
-
+#if 0
 static const struct ehci_companions ich9_1d[] = {
     { .name = TYPE_ICH9_USB_UHCI(1), .func = 0, .port = 0 },
     { .name = TYPE_ICH9_USB_UHCI(2), .func = 1, .port = 2 },
@@ -91,7 +91,7 @@ static const struct ehci_companions ich9
     { .name = TYPE_ICH9_USB_UHCI(5), .func = 1, .port = 2 },
     { .name = TYPE_ICH9_USB_UHCI(6), .func = 2, .port = 4 },
 };
-
+#endif
 static int ehci_create_ich9_with_companions(PCIBus *bus, int slot)
 {
     const struct ehci_companions *comp;
@@ -239,9 +239,11 @@ static void pc_q35_init(MachineState *ma
     lpc_dev = DEVICE(lpc);
     qdev_prop_set_bit(lpc_dev, "smm-enabled",
                       x86_machine_is_smm_enabled(x86ms));
+#if 1
     for (i = 0; i < IOAPIC_NUM_PINS; i++) {
         qdev_connect_gpio_out_named(lpc_dev, ICH9_GPIO_GSI, i, x86ms->gsi[i]);
     }
+#endif
     pci_realize_and_unref(lpc, pcms->pcibus, &error_fatal);
 
     x86ms->rtc = ISA_DEVICE(object_resolve_path_component(OBJECT(lpc), "rtc"));
@@ -283,7 +285,7 @@ static void pc_q35_init(MachineState *ma
     /* init basic PC hardware */
     pc_basic_device_init(pcms, isa_bus, x86ms->gsi, x86ms->rtc, !mc->no_floppy,
                          0xff0104);
-
+#if 0
     if (pcms->sata_enabled) {
         PCIDevice *pdev;
         AHCIPCIState *ich9;
@@ -305,7 +307,6 @@ static void pc_q35_init(MachineState *ma
         /* Should we create 6 UHCI according to ich9 spec? */
         ehci_create_ich9_with_companions(pcms->pcibus, 0x1d);
     }
-
     if (pcms->smbus_enabled) {
         PCIDevice *smb;
 
@@ -321,6 +322,7 @@ static void pc_q35_init(MachineState *ma
 
     /* the rest devices to which pci devfn is automatically assigned */
     pc_vga_init(isa_bus, pcms->pcibus);
+#endif
     pc_nic_init(pcmc, isa_bus, pcms->pcibus);
 
     if (machine->nvdimms_state->is_enabled) {
@@ -359,12 +361,13 @@ static void pc_q35_machine_options(Machi
     m->desc = "Standard PC (Q35 + ICH9, 2009)";
     m->units_per_default_bus = 1;
     m->default_machine_opts = "firmware=bios-256k.bin";
-    m->default_display = "std";
-    m->default_nic = "e1000e";
+    m->default_display = "none";
+    m->default_nic = "virtio-net-pci";
     m->default_kernel_irqchip_split = false;
     m->no_floppy = 1;
     m->max_cpus = 4096;
-    m->no_parallel = !module_object_class_by_name(TYPE_ISA_PARALLEL);
+    m->no_parallel = 1;
+    m->ignore_boot_device_suffixes = true;
     machine_class_allow_dynamic_sysbus_dev(m, TYPE_AMD_IOMMU_DEVICE);
     machine_class_allow_dynamic_sysbus_dev(m, TYPE_INTEL_IOMMU_DEVICE);
     machine_class_allow_dynamic_sysbus_dev(m, TYPE_RAMFB_DEVICE);
@@ -381,6 +381,7 @@ static void pc_q35_machine_10_2_options(
 
 DEFINE_Q35_MACHINE_AS_LATEST(10, 2);
 
+#if 0
 static void pc_q35_machine_10_1_options(MachineClass *m)
 {
     pc_q35_machine_10_2_options(m);
@@ -695,3 +696,4 @@ static void pc_q35_machine_2_6_options(M
 }
 
 DEFINE_Q35_MACHINE(2, 6);
+#endif
--- a/hw/i386/pc_q35.c	2026-03-31 19:10:11.650911367 +0200
+++ b/hw/i386/pc_q35.c	2026-03-31 19:11:06.445131700 +0200
@@ -91,7 +91,6 @@ static const struct ehci_companions ich9
     { .name = TYPE_ICH9_USB_UHCI(5), .func = 1, .port = 2 },
     { .name = TYPE_ICH9_USB_UHCI(6), .func = 2, .port = 4 },
 };
-#endif
 static int ehci_create_ich9_with_companions(PCIBus *bus, int slot)
 {
     const struct ehci_companions *comp;
@@ -126,6 +125,7 @@ static int ehci_create_ich9_with_compani
     }
     return 0;
 }
+#endif
 
 /* PC hardware initialisation */
 static void pc_q35_init(MachineState *machine)
--- a/hw/core/machine.c	2026-03-31 07:04:12.848337933 +0200
+++ b/hw/core/machine.c	2026-03-31 07:06:08.752070371 +0200
@@ -47,6 +47,7 @@ GlobalProperty hw_compat_10_1[] = {
 };
 const size_t hw_compat_10_1_len = G_N_ELEMENTS(hw_compat_10_1);
 
+#if 0
 GlobalProperty hw_compat_10_0[] = {
     { "scsi-hd", "dpofua", "off" },
     { "vfio-pci", "x-migration-load-config-after-iter", "off" },
@@ -297,6 +298,7 @@ GlobalProperty hw_compat_2_6[] = {
     { "virtio-pci", "disable-legacy", "off", .optional = true },
 };
 const size_t hw_compat_2_6_len = G_N_ELEMENTS(hw_compat_2_6);
+#endif
 
 MachineState *current_machine;
