all: make.sh sources
	sh make.sh

sources: make.sh
	sh make.sh $@

clean: make.sh
	sh make.sh $@

veryclean: clean
	sh make.sh $@

deepclean: veryclean
	sh make.sh $@
  
distclean: deepclean
	sh make.sh $@

