# Minimal config: only q35 and microvm + virtio basics
# No i440fx, no extra junk

# Machines / Boards
# CONFIG_PC=n
CONFIG_Q35=y
CONFIG_MICROVM=y

# Required bus and devices
CONFIG_PCI=y
CONFIG_VIRTIO_PCI=y
CONFIG_VIRTIO_NET=y
CONFIG_VIRTIO_BLK=y
CONFIG_VHOST_NET=y

# Disable everything else aggressively
CONFIG_I440FX=n
CONFIG_ISAPC=n
CONFIG_NITRO_ENCLAVE=n
CONFIG_AMD_IOMMU=n
CONFIG_APPLESMC=n
CONFIG_FDC=n
CONFIG_HPET=n
CONFIG_HYPERV=n
CONFIG_IPMI=n
CONFIG_QXL=n
CONFIG_SEV=n
CONFIG_SGA=n
CONFIG_TDX=n
CONFIG_TEST_DEVICES=n
CONFIG_TPM=n
CONFIG_VTD=n
CONFIG_SGX=n
CONFIG_USB=n
CONFIG_HOTPLUG=n
CONFIG_MPATH=n
CONFIG_NUMA=n
